force-app/main/default/objects/Tarea__c/Tarea__c.object-meta.xml
<CustomObject>
    <description>Tareas pendientes a completar</description>
    <label>Tarea</label>
    <nameField>
        <label>Tarea Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tareas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tarea__c/fields/descripcion__c.field-meta.xml
<CustomField>
    <fullName>descripcion__c</fullName>
    <description>Descripcion de la tarea a realizar</description>
    <label>Descripcion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tarea__c/fields/titulo__c.field-meta.xml
<CustomField>
    <fullName>titulo__c</fullName>
    <label>Titulo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TareaController.cls
public with sharing class TareaController {

    
    @AuraEnabled(cacheable=true)
    public static Tarea__c crearTarea(String titulo, String descripcion){
        try {
            Tarea__c nuevaTarea = new Tarea__c(titulo__c = titulo, descripcion__c = descripcion);
            insert nuevaTarea;
            return nuevaTarea;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}